### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by temap** [szeged/csibe#43]
Hi guys,
your benchmark is listed on https://gcc.gnu.org/benchmarks.

Do you have plans to migrate to Python 3?

**Comment by loki04** [comment]
Currently the Python 3 is not in focus, but all contributions are welcome! I would be glad to review it.

**Comment by temap** [comment]
Hi @loki04 , I created PR. Could you please check?

https://github.com/szeged/csibe/pull/44

Thanks
